language: node_js

node_js:
  - 8
  - 6

env:
  - WEBPACK_VERSION=4.0.0-beta.2
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=2
  - WEBPACK_VERSION=1

matrix:
  fast_finish: true

before_install:
  # Install Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true
  directories:
    - node_modules
    - cache

before_script:
  - yarn add webpack@$WEBPACK_VERSION
